import gmsh, sys, math, time
name, h = sys.argv[1], float(sys.argv[2])
gmsh.initialize(); gmsh.option.setNumber("General.Terminal",0)
gmsh.merge(f'work/half_{name}.stl')
gmsh.model.mesh.classifySurfaces(15*math.pi/180, True, True, 15*math.pi/180)
gmsh.model.mesh.createGeometry()
s=gmsh.model.getEntities(2)
l=gmsh.model.geo.addSurfaceLoop([e[1] for e in s]); gmsh.model.geo.addVolume([l]); gmsh.model.geo.synchronize()
gmsh.option.setNumber("Mesh.MeshSizeMax",h); gmsh.option.setNumber("Mesh.MeshSizeMin",h*0.3)
gmsh.option.setNumber("Mesh.Algorithm",6); gmsh.option.setNumber("Mesh.Algorithm3D",10)
gmsh.option.setNumber("Mesh.ElementOrder",2); gmsh.option.setNumber("Mesh.HighOrderOptimize",0)
gmsh.option.setNumber("Mesh.SecondOrderLinear",0)
t=time.time()
gmsh.model.mesh.generate(3)
et,tags,_=gmsh.model.mesh.getElements(3)
print(name,'surfaces',len(s),'tets',sum(len(x) for x in tags),'time',round(time.time()-t,1))
gmsh.option.setNumber("Mesh.SaveAll",0)
gmsh.model.addPhysicalGroup(3,[gmsh.model.getEntities(3)[0][1]],1)
gmsh.write(f'work/mesh_{name}.msh')
gmsh.finalize()
